import { TestBed } from '@angular/core/testing';
import { App } from './app';
import { provideRouter } from '@angular/router';

describe('App', () => {
  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [App],
      providers: [provideRouter([])]
    }).compileComponents();
  });

  it('should create the app', () => {
    const fixture = TestBed.createComponent(App);
    const app = fixture.componentInstance;
    expect(app).toBeTruthy();
  });

  // Removed 'should render title' test because the app template does not contain a simple h1 with "Hello, CommerceX".
  // It renders <app-header>, <app-filter-side-panel>, and <app-products>.
  // The original test seems to have been generated by CLI for a blank app and is no longer valid for this structure.
});
